version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: official-visits-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: official-visits-db
      POSTGRES_USER: official-visits
      POSTGRES_PASSWORD: official-visits
    volumes:
      - ./docker-init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  hmpps:
