TRUNCATE TABLE official_visit  RESTART IDENTITY CASCADE;
TRUNCATE TABLE prisoner_visited RESTART IDENTITY CASCADE;
TRUNCATE TABLE official_visitor RESTART IDENTITY CASCADE;
TRUNCATE TABLE visitor_equipment RESTART IDENTITY CASCADE;
