apiVersion: batch/v1
kind: CronJob
metadata:
  name: process-review-candidates
spec:
  schedule:  "{{ .Values.cron.processReviewCandidatesJob }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 5
  timeZone: "Europe/London"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      activeDeadlineSeconds: 2400
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: process-review-candidates-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -XPOST http://hmpps-official-visits-api/job-admin/run/PROCESS_REVIEW_CANDIDATES
          restartPolicy: Never